- block:
  - name: 准备etcd-ca证书目录等
    file: name={{ item }} state=directory
    with_items:
    - "{{ cluster_dir }}/ssl"
    - "{{ cluster_dir }}/backup"

  # 注册变量p，根据p的stat信息判断是否已经生成过etcd-ca证书，如果没有，下一步生成证书
  # 如果已经有etcd-ca证书，为了保证整个安装的幂等性，跳过证书生成的步骤
  - name: 读取etcd-ca证书stat信息
    stat: path="{{ cluster_dir }}/ssl/etcd-ca.pem"
    register: p

  - name: 准备etcd-ca配置文件和签名请求
    template: src={{ item }}.j2 dest={{ cluster_dir }}/ssl/{{ item }}
    with_items:
    - "etcd-ca-config.json"
    - "etcd-ca-csr.json"
    when: "p.stat.isreg is not defined"

  - name: 生成 CA 证书和私钥
    when: "p.stat.isreg is not defined"
    shell: "cd {{ cluster_dir }}/ssl && \
       {{ base_dir }}/bin/cfssl gencert -initca etcd-ca-csr.json | {{ base_dir }}/bin/cfssljson -bare etcd-ca"

  - name: 创建etcd证书请求
    template: src=etcd-csr.json.j2 dest={{ cluster_dir }}/ssl/etcd-csr.json

  - name: 创建 etcd证书和私钥
    shell: "cd {{ cluster_dir }}/ssl && {{ base_dir }}/bin/cfssl gencert \
          -ca=etcd-ca.pem \
          -ca-key=etcd-ca-key.pem \
          -config=etcd-ca-config.json \
          -profile=kubernetes etcd-csr.json | {{ base_dir }}/bin/cfssljson -bare etcd"
  connection: local
  run_once: true

- name: 准备etcd-ca证书目录等
  file: name={{ item }} state=directory
  with_items:
  - "{{ ca_dir }}"
  - "{{ etcd_ca_dir }}"
  - "{{ ETCD_DATA_DIR }}"

- name: 下载etcd二进制文件
  copy: src={{ base_dir }}/bin/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - etcd
  - etcdctl
  tags: upgrade_etcd

- name: 分发etcd证书相关
  copy: src={{ cluster_dir }}/ssl/{{ item }} dest={{ etcd_ca_dir }}/{{ item }}
  with_items:
  - etcd-ca.pem
  - etcd.pem
  - etcd-key.pem

- name: 复制etcd证书
  shell: "cp -f {{ etcd_ca_dir }}/* {{ ca_dir }}"

- name: 创建etcd的systemd unit文件
  template: src=etcd.service.j2 dest=/etc/systemd/system/etcd.service
  tags: upgrade_etcd, restart_etcd

- name: 开机启用etcd服务
  shell: systemctl enable etcd
  ignore_errors: true

- name: 开启etcd服务
  shell: systemctl daemon-reload && systemctl restart etcd
  ignore_errors: true
  tags: upgrade_etcd, restart_etcd

- name: 以轮询的方式等待服务同步完成
  shell: "systemctl is-active etcd.service"
  register: etcd_status
  until: '"active" in etcd_status.stdout'
  retries: 8
  delay: 8
  tags: upgrade_etcd, restart_etcd
