# [optional] to synchronize system time of nodes with 'chrony' 
- hosts:
  - control_plane
  - work_node
  - chrony
  roles:
  - { role: chrony, when: "groups['chrony']|length > 0" }

# prepare tasks for all nodes
- hosts:
  - control_plane
  - work_node
  roles:
  - prepare

# to install etcd cluster
- hosts: control_plane 
  roles:
  - etcd

# to install a container runtime
- hosts:
  - control_plane
  - work_node
  roles:
  - containerd 

# to set up 'control_plane' nodes
- hosts: control_plane
  roles:
  - control-plane 

# to install network plugin, only one can be choosen 
- hosts:
  - control_plane 
  - work_node
  roles:
  - { role: calico, when: "CLUSTER_NETWORK == 'calico'" }
  - { role: cilium, when: "CLUSTER_NETWORK == 'cilium'" }
  - { role: flannel, when: "CLUSTER_NETWORK == 'flannel'" }
