- hosts: etcd
  tasks:
  - name: starting etcd cluster
    service: name=etcd state=started enabled=yes

- hosts:
  - control_plane
  - work_node
  tasks:
  - name: starting kube-lb
    service: name=kube-lb state=started enabled=yes

- hosts: control_plane
  tasks:
  - name: starting control_plane services
    service: name={{ item }} state=started enabled=yes
    with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

- hosts:
  - control_plane
  - work_node
  tasks:
  - name: starting docker
    service: name=docker state=started enabled=yes
    when: "CONTAINER_RUNTIME == 'docker'"

  - name: starting containerd
    service: name=containerd state=started enabled=yes
    when: "CONTAINER_RUNTIME == 'containerd'"

  - name: starting work_node services
    service: name={{ item }} state=started enabled=yes
    with_items:
    - kubelet
    - kube-proxy

- hosts: ex_lb
  tasks:
  - name: starting external loadbalance
    service: name={{ item }} state=started enabled=yes
    with_items:
    - haproxy
    - keepalived
